" vim: set filetype=vim :

" paths {{{1

" avoid to read specific legacy vim conf
set runtimepath-=/usr/share/vim/vimfiles

" load vim-qt files

set runtimepath+=/usr/share/nvim-qt/runtime

" lilypond {{{2

" interfere with config
"
" filetype off
" set runtimepath+=/usr/share/vim/vimfiles
" filetype on
" syntax on

" plugins needed before config {{{1

packadd matchit

" main {{{1

source ~/racine/config/edit/vim/main.vim

" auto-commands {{{1

source ~/racine/config/edit/vim/autocommand.vim

" python {{{1

if ['arch', 'manjaro', 'artix', 'void', 'ubuntu', 'linux']->index($OPERASYS) >= 0
	let g:python3_host_prog = '/bin/python3'
	let g:python_host_prog = '/bin/python2'
elseif $OPERASYS == 'freebsd'
	let g:python3_host_prog = '/usr/local/bin/python3'
	let g:python_host_prog = '/usr/local/bin/python2'
endif

" all remaining plugins {{{1

source ~/racine/config/edit/vim/paquet/packager.vim
source ~/racine/config/edit/vim/paquet/preload.vim

" load everything to be able to use some conf functions

packloadall

" plugins autoload functions call have to stand after packloadall

source ~/racine/config/edit/vim/paquet/postload.vim

" maps replacing plugins ones {{{1

" plugins auto-commands {{{1

source ~/racine/config/edit/vim/paquet/autocmd-plugin.vim

" lua {{{1

lua require('meta')
