# Inspired by :
# Author : Jakub Bartodziej <kubabartodziej@gmail.com>
# The theme uses the gruvbox dark palette with standard contrast: github.com/morhetz/gruvbox

"attribute" = "#5b3c11"
"keyword" = { fg = "#872e30" }
"keyword.directive" = "#5b3c11"
"namespace" = "#5b3c11"
"punctuation" = "#5b3c11"
"punctuation.delimiter" = "#5b3c11"
"operator" = "#5b3c11"
"special" = "#88421d"
"variable.other.member" = "#5b3c11"
"variable" = "#5b3c11"
"variable.builtin" = "#5b3c11"
"variable.parameter" = "#5b3c11"
"type" = "#5b3c11"
"type.builtin" = "#5b3c11"
"constructor" = { fg = "#5b3c11" }
"function" = { fg = "#5b3c11" }
"function.macro" = "#5b3c11"
"function.builtin" = "#5b3c11"
"tag" = "#872e30"
"comment" = { fg = "#754321", modifiers = ["italic"]  }
"constant" = { fg = "#88421d" }
"constant.builtin" = { fg = "#5b3c11" }
"string" = "#5b3c11"
"constant.numeric" = "#5b3c11"
"constant.character.escape" = { fg = "#5b3c11" }
"label" = "#5b3c11"
"module" = "#5b3c11"

"diff.plus" = "#5b3c11"
"diff.delta" = "#5b3c11"
"diff.minus" = "#5b3c11"

"warning" = "orange1"
"error" = "red1"
"info" = "aqua1"
"hint" = "blue1"

"ui.background" = { bg = "bg0" }
"ui.linenr" = { fg = "#5b3c11" }
"ui.linenr.selected" = { fg = "#5b3c11", modifiers = ["italic"] }
"ui.cursorline" = { bg = "bg1" }
"ui.statusline" = { fg = "fg1", bg = "#120705", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "fg1", bg = "#120705", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "fg1", bg = "#071205", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "fg1", bg = "#070512", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg1", modifiers = ["bold"] }
"ui.popup" = { bg = "bg1" }
"ui.window" = { bg = "bg1" }
"ui.help" = { bg = "#000000", fg = "#5b3c11" }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "fg1" }
"ui.selection" = { fg = "#000000", bg = "#5b3c11", modifiers = ["bold"] }
"ui.selection.primary" = { fg = "#000000", bg = "#88421d", modifiers = ["bold"] }
"ui.cursor.primary" = { fg = "#000000", bg = "#872e30"}
"ui.cursor.match" = { bg = "bg3" }
"ui.menu" = { fg = "#88421d", bg = "#070707" }
"ui.menu.selected" = { fg = "#ab1c11", bg = "#070707", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.inlay-hint" = { fg = "gray1" }
"ui.virtual.wrap" = { fg = "bg2" }

"diagnostic.warning" = { underline = { color = "orange1", style = "curl" } }
"diagnostic.error" = { underline = { color = "red1", style = "curl" } }
"diagnostic.info" = { underline = { color = "aqua1", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue1", style = "curl" } }

"markup.heading" = "aqua1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green1", modifiers = ["underlined"] }
"markup.link.text" = "red1"
"markup.raw" = "red1"

[palette]
bg0 = "#000000" # main background
bg1 = "#3c3836"
bg2 = "#504945"
bg3 = "#665c54"
bg4 = "#7c6f64"

fg0 = "#fbf1c7"
fg1 = "#5b3c11" # main foreground
fg2 = "#d5c4a1"
fg3 = "#bdae93"
fg4 = "#a89984" # gray0

gray0 = "#a89984"
gray1 = "#928374"

red0 = "#cc241d" # neutral
red1 = "#fb4934" # bright
green0 = "#98971a"
green1 = "#b8bb26"
yellow0 = "#d79921"
yellow1 = "#fabd2f"
blue0 = "#458588"
blue1 = "#83a598"
purple0 = "#b16286"
purple1 = "#d3869b"
aqua0 = "#689d6a"
aqua1 = "#8ec07c"
orange0 = "#d65d0e"
orange1 = "#fe8019"
