
[common]
# Whether to use ANSI color in output
color = true

# Enable debug logging, shows HTTP requests
debug = true

# Redirect debug log to the given file
debug_file = "log/toot.log"

# Log request and response bodies in the debug log
verbose = false

# Do not write to output
quiet = false

[commands.post]
editor = "vim"
sensitive = true
visibility = "unlisted"
scheduled_in = "30 minutes"

[tui]
colors = 16

[tui.palette]
account = ["dark green", ""]
button = ["", ""]
button_focused = ["dark red", ""]
card_author = ["", ""]
card_title = ["", ""]
columns_divider = ["", ""]
content_warning = ["", ""]
editbox = ["", ""]
editbox_focused = ["brown", ""]
footer_message = ["dark green", ""]
footer_message_error = ["dark red, bold", ""]
footer_status = ["brown", ""]
footer_status_bold = ["brown, bold", ""]
hashtag = ["brown", ""]
hashtag_followed = ["dark red", ""]
header = ["brown", ""]
header_bold = ["brown, bold", ""]
intro_bigtext = ["dark green", ""]
intro_smalltext = ["dark green", ""]
links = [",italics", ""]
links_focused = [",italics", ""]
poll_bar = ["", ""]
shortcut = ["dark green", ""]
shortcut_highlight = ["dark red", ""]
status_detail_account = ["", ""]
status_detail_bookmarked = ["", ""]
status_detail_timestamp = ["", ""]
status_list_account = ["", ""]
status_list_selected = ["dark red", ""]
status_list_timestamp = ["", ""]
warning = ["dark red", ""]
