" vim: set filetype=vim :

source ~/racine/config/edit/vim/defaut.vim

"  {{{ Historique
" ------------------------------------------------------------------------

set viminfo=
	\!,
	\f1,
	\c,
	\h,
	\<12,
	\s12,
	\'60,
	\:7543,
	\/1234,
	\@1234,
	\n~/racine/hist/vim/main.info

" Remplacé par neomru
"	\%,

" Nombre par défaut pour lignes de commande,
" recherches, nombre de lignes d’entrée

set history=7500

" }}}

"  {{{ Plugins
" ------------------------------------------------------------------------

if $OPERASYS == 'archlinux'

	let g:python3_host_prog = '/bin/python3'

	let g:python_host_prog = '/bin/python2'

elseif $OPERASYS == 'freebsd'

	let g:python3_host_prog = '/usr/local/bin/python3'

	let g:python_host_prog = '/usr/local/bin/python2'

endif

source ~/racine/config/edit/vim/paquet/plugged.vim

source ~/racine/config/edit/vim/paquet/config.vim

" }}}

"  {{{ Auto-commandes pour plugins
" ------------------------------------------------------------------------

source ~/racine/config/edit/vim/autocmd_plugin.vim

" }}}
