#! /bin/zsh

# Autostart {{{1

# Générique

autostart.zsh

# Spécifique à bspwm

alias psgrep='ps auxww | grep -v grep | grep --color=never'

psgrep sxhkd || sxhkd >>&! ~/log/sxhkd.log &

polybar.zsh

# }}}1

bspc rule -r "*"

# Monitor {{{1

bspc monitor -d term text browser office artisan entertain misc

# bspc monitor eDP1 -d term text browser office artisan entertain misc
# bspc monitor HDMI1 -d movie cartoon sport

# }}}1

# Desktops {{{1

bspc desktop -f term

# }}}1

# Config {{{1

bspc config automatic_scheme            spiral

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# }}}1

# Rules {{{1

# Desktops {{{2

bspc rule -a kitty desktop=term
bspc rule -a XTerm desktop=term

bspc rule -a Gvim desktop=text
bspc rule -a nvim-qt desktop=text
bspc rule -a Emacs desktop=text

bspc rule -a qutebrowser desktop=browser
bspc rule -a firefox desktop=browser
bspc rule -a Brave-browser desktop=browser
bspc rule -a Thunderbird desktop=browser

bspc rule -a Zathura desktop=office

bspc rule -a GeoGebra desktop=artisan
bspc rule -a MuseScore3 desktop=artisan

bspc rule -a libreoffice-startcenter desktop=office

bspc rule -a vlc desktop=entertain

bspc rule -a net-sourceforge-jnlp-runtime-Boot desktop=misc
bspc rule -a sun-awt-X11-XFramePeer desktop=misc
bspc rule -a java-lang-Thread desktop=misc

# }}}2

# Tiled {{{2

bspc rule -a Emacs  state=tiled

# }}}2

# Floating {{{2

bspc rule -a XClock                     state=floating

bspc rule -a URxvt                      state=floating

bspc rule -a Vimiv                      state=floating
bspc rule -a Sxiv                       state=floating

bspc rule -a Pavucontrol                state=floating

bspc rule -a Zenity                     state=floating
bspc rule -a Xfce4-appfinder            state=floating
bspc rule -a Pamac-manager              state=floating
bspc rule -a Caja                       state=floating
bspc rule -a "Manjaro Settings Manager" state=floating
bspc rule -a Asunder                    state=floating

bspc rule -a net-sourceforge-jnlp-runtime-Boot state=floating
bspc rule -a sun-awt-X11-XFramePeer            state=floating
bspc rule -a java-lang-Thread                  state=floating

# }}}2

# }}}1
