#! /bin/zsh

# Autostart {{{1

autostart.zsh

# }}}1

bspc rule -r "*"

# Monitor {{{1

bspc monitor -d term edit browser office artisan entertain misc

# bspc monitor eDP1 -d term edit browser office artisan entertain misc
# bspc monitor HDMI1 -d movie cartoon sport

# }}}1

# Desktops {{{1

#bspc desktop -f term

# }}}1

# Config {{{1

bspc config automatic_scheme     spiral

bspc config pointer_action1      move
bspc config pointer_action2      resize_size
bspc config pointer_action3      resize_corner

bspc config pointer_modifier1    Mod4
bspc config pointer_modifier2    Mod4
bspc config pointer_modifier3    Mod4

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#000000'
bspc config active_border_color  '#7b3c11'
bspc config focused_border_color  '#7b3c11'

bspc config presel_feedback_color "#301207"

# Pas besoin avec picom
# bspc config focused_frame_opacity 1.0
# bspc config normal_frame_opacity 0.85

# }}}1

# Rules {{{1

# Desktops {{{2

bspc rule -a kitty desktop=term

bspc rule -a Gvim desktop=edit
bspc rule -a nvim-qt desktop=edit
bspc rule -a Emacs desktop=edit

bspc rule -a qutebrowser desktop=browser
bspc rule -a firefox desktop=browser
bspc rule -a Brave-browser desktop=browser
bspc rule -a Thunderbird desktop=browser

bspc rule -a Zathura desktop=office

bspc rule -a GeoGebra desktop=artisan
bspc rule -a MuseScore3 desktop=artisan

bspc rule -a libreoffice-startcenter desktop=office

bspc rule -a vlc desktop=entertain

bspc rule -a net-sourceforge-jnlp-runtime-Boot desktop=misc
bspc rule -a sun-awt-X11-XFramePeer desktop=misc
bspc rule -a java-lang-Thread desktop=misc

# }}}2

# Tiled {{{2

bspc rule -a Emacs  state=tiled

# }}}2

# Floating {{{2

bspc rule -a XClock                     state=floating rectangle=250x250+1630+50

bspc rule -a URxvt:zshrun               state=floating
bspc rule -a URxvt:zshrunterm           state=floating

bspc rule -a URxvt:calculatrice         state=floating
bspc rule -a URxvt:meteo                state=floating
bspc rule -a URxvt:journal              state=floating rectangle=1200x500+350+50
bspc rule -a URxvt:maintenance          state=floating rectangle=1200x500+350+50
bspc rule -a URxvt:multimedia           state=floating

bspc rule -a Vimiv                      state=floating
bspc rule -a Sxiv                       state=floating

bspc rule -a Pavucontrol                state=floating

bspc rule -a Zenity                     state=floating
bspc rule -a Xfce4-appfinder            state=floating
bspc rule -a Pamac-manager              state=floating
bspc rule -a Caja                       state=floating
bspc rule -a "Manjaro Settings Manager" state=floating
bspc rule -a Asunder                    state=floating

bspc rule -a net-sourceforge-jnlp-runtime-Boot state=floating
bspc rule -a sun-awt-X11-XFramePeer            state=floating
bspc rule -a java-lang-Thread                  state=floating

# }}}2

# Dropdown {{{2

# rectangle=width x height + Xoffset + Yoffset

bspc rule -a kitty:dropdown sticky=on state=floating rectangle=1500x700+200+40
bspc rule -a URxvt:dropdown sticky=on state=floating rectangle=964x574+476+50

# }}}2

# }}}1
