#colorscheme golden-night
#colorscheme base16
#colorscheme desertex
colorscheme gruvbox-dark
#colorscheme lucius
#colorscheme tomorrow-night
#colorscheme zenburn

# Options
# ------------------------------

set-option global scrolloff 5,0
set-option global autowrap_column 80

add-highlighter global/ number-lines -relative

# Hooks
# ------------------------------

# hook global WinCreate ^[^*]+$ %{ add-highlighter window/number-lines number-lines -relative }
# hook global WinCreate ^[^*]+$ %{ add-highlighter global/wrap wrap }

# hook global WinCreate .* %{ add-highlighter window/number-lines number-lines -relative }
# hook global WinCreate .* %{ add-highlighter global/wrap wrap }

hook global KakEnd .* %{ echo -to-file %sh{echo $HOME/racine/hist/kak/history } -quoting kakoune reg : %reg{:} }
hook global KakEnd .* %sh{ tail -n 1000 $HOME/racine/hist/kak/history | sponge $HOME/racine/hist/kak/history }
hook global KakBegin .* %{ try %{ source %sh{echo $HOME/racine/hist/kak/history } } }

# Maps
# ------------------------------
 
map global normal ^ gh
map global normal $ gl

map global normal <a-$> $

map global normal x d
map global normal µ x

map global normal <c-pagedown> ': buffer-next <ret>'
map global normal <c-pageup> ': buffer-previous <ret>'
map global normal <c-del> ': delete-buffer<ret>'

map global normal = '| fmt -w $kak_opt_autowrap_column<ret>'

map global normal <c-l> 'vv'

# copy X clipboard
 
map global normal <c-p> '| xclip -o -selection primary <ret> '

# User maps : prefix <space> 
# ------------------------------

map global user 'c' ': edit ~/racine/config/edit/kak/kakrc<ret>'
map global user 'r' ': source ~/racine/config/edit/kak/kakrc<ret>'

map global user ';' '<a-.>'
map global user '|' '<a-|>'

map global user 'j' ': vertical-selection-down<ret>'
map global user 'k' ': vertical-selection-up<ret>'
map global user 'o' ': vertical-selection-up-and-down<ret>'

map global user 'Z' ': write-quit<ret>'
map global user 'Q' ': quit<ret>'

# Commandes
# ------------------------------
 
define-command -override cd change-directory
define-command -override bd delete-buffer

define-command -override wa write-all
define-command -override wq write-quit
define-command -override x write-quit

# Plugins
# ------------------------------

# plug.kak : plugin manager

source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "robertmeta/plug.kak" noload

# FZF

plug "andreyorst/fzf.kak" depth-sort

map global normal 'ù' ': fzf-mode<ret>'

# user modes

plug 'delapouite/kakoune-buffers' %{
  # map global normal ^ q
  # map global normal <a-^> Q
  # map global normal q b
  # map global normal Q B
  # map global normal <a-q> <a-b>
  # map global normal <a-Q> <a-B>
  map global user b ': enter-buffers-mode<ret>' -docstring 'buffers'
  map global user B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
}

plug 'delapouite/kakoune-user-modes' %{
  # Suggested mappings
  map global user a ': enter-user-mode anchor<ret>'   -docstring 'anchor mode'
  map global user e ': enter-user-mode echo<ret>'     -docstring 'echo mode'
  map global user f ': enter-user-mode format<ret>'   -docstring 'format mode'
  map global user i ': enter-user-mode enter<ret>'    -docstring 'enter mode'
  map global user k ': enter-user-mode keep<ret>'     -docstring 'keep mode'
  map global user l ': enter-user-mode lint<ret>'     -docstring 'lint mode'
  map global user @ ': enter-user-mode rotation<ret>' -docstring 'rotation mode'
  map global user t ': enter-user-mode trim<ret>'     -docstring 'trim mode'
  map global user / ': enter-user-mode search<ret>'   -docstring 'search mode'
}# Vertical-selection

# Text objects

plug "delapouite/kakoune-text-objects" %{
    text-object-map
}

# vertical selection

plug "occivink/kakoune-vertical-selection" %{
    map global user s ': enter-user-mode selectors<ret>' -docstring 'selectors'
}
