[key_bindings]
    AUTOCLEAR = "c"
    CANCEL = "esc"
    ENTER = "enter"
    FILTER = ["F4", "\\"]
    FOLLOW_ROW = "F"
    HELP = ["F1", "?"]
    MOVE_DOWN = ["down", "j"]
    MOVE_DOWN_STEP = "J"
    MOVE_END = "end"
    MOVE_HOME = "home"
    MOVE_LEFT = ["left", "h"]
    MOVE_RIGHT = ["right", "l"]
    MOVE_UP = ["up", "k"]
    MOVE_UP_STEP = "K"
    NEXT_SORT = ["p", ">"]
    PREVIOUS_SORT = "<"
    PRIORITY_DOWN = ["F8", "d", "]"]
    PRIORITY_UP = ["F7", "u", "["]
    QUIT = ["F10", "q"]
    REMOVE_ASK = ["del", "F9"]
    RETRY = "r"
    RETRY_ALL = "R"
    REVERSE_SORT = "I"
    SEARCH = ["F3", "/"]
    SELECT_SORT = "F6"
    SETUP = "F2"
    TOGGLE_EXPAND_COLLAPSE = "x"
    TOGGLE_EXPAND_COLLAPSE_ALL = "X"
    TOGGLE_RESUME_PAUSE = "space"
    TOGGLE_RESUME_PAUSE_ALL = "P"
    TOGGLE_SELECT = "s"
    UN_SELECT_ALL = "U"
    ADD_DOWNLOADS = "a"

[colors]
    BRIGHT_HELP = "DEFAULT NORMAL BLACK"
    HEADER = "DEFAULT NORMAL BLACK"
    FOCUSED_HEADER = "DEFAULT UNDERLINE BLACK"
    FOCUSED_ROW = "GREEN NORMAL BLACK"
    SIDE_COLUMN_FOCUSED_ROW = "BLACK NORMAL DEFAULT"
    SIDE_COLUMN_HEADER = "DEFAULT NORMAL BLACK"
    SIDE_COLUMN_ROW = "DEFAULT NORMAL BLACK"
    STATUS_ACTIVE = "DEFAULT NORMAL BLACK"
    STATUS_COMPLETE = "DEFAULT NORMAL BLACK"
    STATUS_PAUSED = "DEFAULT NORMAL BLACK"
    STATUS_WAITING = "DEFAULT NORMAL BLACK"
    STATUS_ERROR = "RED NORMAL BLACK"
    METADATA = "DEFAULT NORMAL BLACK"
