#!/usr/bin/env zsh

# this is a simple config for herbstluftwm

# path {{{1

source ~/racine/config/cmdline/zsh/zprofile

# alias {{{1

hc() {
    herbstclient "$@"
}

# hook {{{1

hc emit_hook reload

#xsetroot -solid '#5A8E3A'

# tags, aka desktops aka workspaces {{{1

tag_names=(term visu edit system browser office artisan video game)

hc rename default $tag_names[1] || true

for index in {1..9}
do
    hc add $tag_names[$index]
done

# keybindings {{{1

# unbind {{{2

# remove all existing keybindings

hc keyunbind --all

# modifiers {{{2

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

super=Mod4   # Use the super key as the main modifier
hyper=Mod3   # Use the super key as the main modifier

# self {{{2

#hc keybind $hyper-Shift-q quit
#hc keybind $super-Shift-q quit

hc keybind $hyper-r reload

hc keybind $hyper-BackSpace close_and_remove
hc keybind $hyper-Shift-x close_and_remove

# focus {{{2

hc keybind $super-Left  focus left
hc keybind $super-Down  focus down
hc keybind $super-Up    focus up
hc keybind $super-Right focus right

hc keybind $super-Tab cycle +1
hc keybind $super-BackSpace cycle -1

# movement {{{2

# moving clients in tiling and floating mode

# with the option focus_crosses_monitor_boundaries,
# can also move the window to another monitor

hc keybind $hyper-Left  shift left
hc keybind $hyper-Down  shift down
hc keybind $hyper-Up    shift up
hc keybind $hyper-Right shift right

hc keybind $super-Next spawn hlwm-swap.bash down
hc keybind $super-Prior spawn hlwm-swap.bash up

# splitting frames {{{2

# create an empty frame at the specified direction

hc keybind $hyper-h       split   bottom  0.618
hc keybind $hyper-v       split   right   0.618

# let the current frame explode into subframes

hc keybind $super-Control-space split explode

# resizing frames and floating clients {{{2

resizestep=0.02

hc keybind $super-Control-Left    resize left +$resizestep
hc keybind $super-Control-Down    resize down +$resizestep
hc keybind $super-Control-Up      resize up +$resizestep
hc keybind $super-Control-Right   resize right +$resizestep

# focus {{{2

#hc keybind $super-BackSpace   cycle_monitor
#hc keybind $super-Tab         cycle_all +1
#hc keybind $super-Shift-Tab   cycle_all -1

#hc keybind $super-c cycle
#hc keybind $super-i jumpto urgent

# tags, aka desktops aka workspaces {{{2

hc keybind $hyper-Prior use_index -1
hc keybind $hyper-Next use_index +1

for index in {1..9}
do
	key=F$index
	(( workspace = index - 1 ))
	hc keybind $super-$key use_index $workspace
	hc keybind $super-Shift-$key move_index $workspace
done

#tag_names=( {1..9} )
#tag_keys=( {1..9} 0 )

#hc rename default "${tag_names[0]}" || true
#for i in "${!tag_names[@]}" ; do
    #hc add "${tag_names[$i]}"
    #key="${tag_keys[$i]}"
    #if [ -n "$key" ] ; then
        #hc keybind "$super-$key" use_index "$i"
        #hc keybind "$super-Shift-$key" move_index "$i"
    #fi
#done

# layouting {{{2

hc keybind $hyper-Delete remove

hc keybind $hyper-f floating toggle

hc keybind $hyper-m chain , set_layout max , attr theme.title_height 13
hc keybind $hyper-g chain , set_layout grid , attr theme.title_height 0
hc keybind $hyper-Shift-m spawn hlwm-maximize.sh
hc keybind $hyper-z fullscreen toggle

#hc keybind $super-Shift-f set_attr clients.focus.floating toggle
hc keybind $super-Shift-d set_attr clients.focus.decorated toggle

hc keybind $hyper-Shift-m set_attr clients.focus.minimized true
hc keybind $hyper-Control-m jumpto last-minimized

hc keybind $hyper-p pseudotile toggle

hc keybind $hyper-l cycle_layout +1 horizontal vertical grid max

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.

# hc keybind $hyper-Shift-l                                                       \
#             or , and . compare tags.focus.curframe_wcount = 2                   \
#                      . cycle_layout +1 vertical horizontal max vertical grid    \
#                , cycle_layout +1

# monitors {{{2

# -- to move a window to another monitor,
# -- see the movement keybindings
#hc keybind $hyper-Left chain , shift_to_monitor -l , focus_monitor -l
#hc keybind $hyper-Right chain , shift_to_monitor -r , focus_monitor -r

hc keybind $super-End focus_monitor -1
hc keybind $super-Home focus_monitor +1

hc keybind $super-Shift-Left focus_monitor -l
hc keybind $super-Shift-Right focus_monitor -r

hc keybind $hyper-Tab use_previous
hc keybind $hyper-asciicircum use_previous

# scratchpad {{{2

hc keybind Shift-F12 spawn hlwm-scratchpad.sh

# applications {{{2

#hc keybind $super-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback

hc keybind $hyper-Return spawn xterm -ls zsh
hc keybind $hyper-exclam spawn urxvtc
hc keybind $hyper-dollar spawn kitty

# mouse bindings {{{1

hc mouseunbind --all

hc mousebind $super-Button1 move
hc mousebind $super-Button2 zoom
hc mousebind $super-Button3 resize

# options {{{1

# layout {{{2

hc set tabbed_max 7

# monitors {{{2

hc set auto_detect_monitors 1
hc set focus_crosses_monitor_boundaries 1

# miscellaneous {{{2

hc set tree_style '╾│ ├└╼─┐'

# theme {{{1

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_gap 5
hc set show_frame_decorations 'focused_if_multiple'

hc set frame_border_active_color '#7b3c11cc'
hc set frame_bg_active_color '#000000aa'
hc set frame_border_normal_color '#3b3c11cc'
hc set frame_bg_normal_color '#000000aa'

hc set frame_border_width 1
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_padding 0
hc set smart_frame_surroundings on

hc set window_gap 0
hc set mouse_recenter_gap 0
hc set smart_window_surroundings off

# alias for theme.active.color
#hc set window_border_active_color '#7b3c11cc'
# alias for theme.normal.color
#hc set window_border_normal_color '#5b3c11cc'

hc attr theme.active.color '#000000'
hc attr theme.urgent.color '#5b3c11dd'
hc attr theme.normal.color '#5b3c11dd'

hc attr theme.active.inner_color '#7b3c11'
hc attr theme.normal.inner_color '#5b3c11'
hc attr theme.urgent.inner_color '#872e30'

hc attr theme.inner_color '#5b3c11'
hc attr theme.outer_color '#5b3c11'
hc attr theme.background_color '#000000'

hc attr theme.inner_width 1
hc attr theme.border_width 3

hc attr theme.active.title_color '#5b3c11'
hc attr theme.normal.title_color '#000000'
hc attr theme.title_height 0
hc attr theme.title_depth 0
hc attr theme.title_when always
hc attr theme.active.title_font 'Dejavu Sans:pixelsize=12 Bold'  # example using Xft
hc attr theme.title_font 'Dejavu Sans:pixelsize=12 Bold'  # example using Xft
#hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 3  # space below the title's baseline

hc attr theme.active.tab_title_color '#5b3c11'
hc attr theme.tab_title_color '#000000'
hc attr theme.active.tab_color '#000000dd'
hc attr theme.active.tab_outer_color '#5b3c11dd'
hc attr theme.tab_color '#5b3c11dd'

hc attr theme.tiling.outer_width 1

hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

# copy inner color to outer_color

for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

# rules {{{1

# unrule all {{{2

hc unrule -F

# focus {{{2

# normally focus new clients
hc rule focus=on

# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on

# desktops {{{2

#hc rule class=XTerm tag=term # move all xterms to tag 3

hc rule class=Zathura tag=visu
hc rule class=Apvlv tag=visu
hc rule class=feh tag=visu
hc rule class=sxiv tag=visu
hc rule class=vimiv tag=visu

hc rule class=nvim-qt tag=edit

hc rule class=TradingView tag=system

hc rule class=qutebrowser tag=browser

hc rule class=libreoffice-startcenter tag=office

hc rule class=frescobaldi tag=artisan

hc rule class=vlc tag=video
hc rule class=FreeTube tag=video

hc rule class=wesnoth tag=game

# floating {{{2

hc rule fixedsize floating=on
hc rule floatplacement=center

hc rule instance=zshrun class=URxvt floating=on floatplacement=center
hc rule instance=zshrunterm class=URxvt floating=on floatplacement=center
hc rule instance=fzf-nova class=URxvt floating=on floatplacement=center
hc rule instance=calculatrice class=URxvt floating=on floatplacement=center
hc rule instance=meteo class=URxvt floating=on floatplacement=center
hc rule instance=journal class=URxvt floating=on floatplacement=center
hc rule instance=maintenance class=URxvt floating=on floatplacement=center
hc rule instance=multimedia class=URxvt floating=on floatplacement=center

hc rule class=Pavucontrol floating=on floatplacement=center
hc rule class=QjackCtl floating=on floatplacement=center

hc rule class=zenity floating=on floatplacement=center
hc rule class=Xfce4-appfinder floating=on floatplacement=center
hc rule class=Pamac-manager floating=on floatplacement=center
hc rule class=Caja floating=on floatplacement=center
hc rule class="Manjaro Settings Manager" floating=on floatplacement=center
hc rule class=Asunder floating=on floatplacement=center
hc rule class=Element floating=on floatplacement=center

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on

# dropdown {{{2

hc rule instance=kitty-dropdown floating=on floatplacement=center
hc rule instance=urxvt-dropdown floating=on floatplacement=center
hc rule instance=calc-dropdown floating=on floatplacement=center

# unmanaged {{{2

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# monitors {{{1

# do multi monitor setup here, e.g.:

#hc set_monitors 1280x1024+0+0 1280x1024+1280+0

# or simply:

hc detect_monitors

# unlock {{{1

# just to be sure

hc unlock

# panel {{{1

# polybar {{{2

# must be launched before services that need system tray

#hc spawn hlwm-polybar.zsh

hlwm-polybar.zsh

# dzen2 {{{2

# # find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
# autostart applications {{{1

# in cas of restart, we need to stop some processes first
hlwm-autostop.zsh >>! ~/log/autostop.log 2>&1
sleep 1
hlwm-autostart.zsh >>! ~/log/autostart.log 2>&1
