#!/usr/bin/env /bin/zsh

musique=$(mpc -f '%file%' | awk '{ if ( NR == 1 ) print $0 }')

musique=${musique##*/}
musique=${musique%.*}
musique=$musique[3,-1]
musique=${musique:gs/-/ /}

print $musique

if [ -n "$BLOCK_BUTTON" ]
then
	(( BLOCK_BUTTON == 1 )) && mpc toggle
	(( BLOCK_BUTTON == 2 )) && mpc next
	(( BLOCK_BUTTON == 3 )) && urxvtc -e ncmpcpp
	(( BLOCK_BUTTON == 4 )) && mpc volume +5
	(( BLOCK_BUTTON == 5 )) && mpc volume -5
fi
