#!/usr/bin/env /bin/zsh

volume=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer -c 0 sget Master))

echo $volume

case $BLOCK_BUTTON in
  1) amixer -c 0 -- set Master 4dB+ ;;
  3) amixer -c 0 -- set Master 4dB- ;;
esac
