#!/usr/bin/env /bin/zsh

volume=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer -c 0 sget Master))

echo $volume

case $BLOCK_BUTTON in
  1) pavucontrol ;;
  3) urxvtc -e alsamixer -c 0 ;;
  4) amixer -c 0 -- set Master 2dB+ ;;
  5) amixer -c 0 -- set Master 2dB- ;;
esac
