#!/usr/bin/env zsh

# Chemins d’accès {{{1

source ~/racine/config/cmdline/zsh/zprofile

# Autostart {{{1

# in cas of restart, we need to stop some processes first
autostop.zsh >>! ~/log/autostop.log 2>&1
sleep 1
autostart.zsh >>! ~/log/autostart.log 2>&1

# Reset all rules {{{1

bspc rule -r "*"

# Monitor {{{1

bspc monitor -d term edit browser office artisan entertain misc

# Desktops {{{1

#bspc desktop -f term

# Config {{{1

bspc config automatic_scheme     spiral

# Move & Resize with modifier + mouse

bspc config pointer_action1      move
bspc config pointer_action2      resize_size
bspc config pointer_action3      resize_corner

# super + mouse

bspc config pointer_modifier1    Mod4
bspc config pointer_modifier2    Mod4
bspc config pointer_modifier3    Mod4

bspc config border_width         5
bspc config window_gap           7

bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  '#000000'
bspc config active_border_color  '#5b3c11'
bspc config focused_border_color  '#5b3c11'

bspc config presel_feedback_color "#301207"

# Pas besoin avec picom
# bspc config focused_frame_opacity 1.0
# bspc config normal_frame_opacity 0.85

# Rules {{{1

# Desktops {{{2

#bspc rule -a kitty desktop=term

bspc rule -a nvim-qt desktop=edit
bspc rule -a Emacs desktop=edit

bspc rule -a qutebrowser desktop=browser
bspc rule -a Nyxt desktop=browser
bspc rule -a firefox desktop=browser
bspc rule -a Brave-browser desktop=browser
bspc rule -a Vivaldi-stable desktop=browser
bspc rule -a Chromium desktop=browser
bspc rule -a Min desktop=browser
bspc rule -a Thunderbird desktop=browser

bspc rule -a Zathura desktop=office
bspc rule -a Apvlv desktop=office
bspc rule -a libreoffice-startcenter desktop=office

bspc rule -a GeoGebra desktop=artisan
bspc rule -a kig desktop=artisan
bspc rule -a MuseScore3 desktop=artisan
bspc rule -a MuseScore3Development desktop=artisan
bspc rule -a MuseScore4 desktop=artisan
bspc rule -a frescobaldi desktop=artisan
bspc rule -a Rosegarden desktop=artisan
bspc rule -a vimiv desktop=artisan
bspc rule -a Sxiv desktop=artisan
bspc rule -a feh desktop=artisan

bspc rule -a vlc desktop=entertain
bspc rule -a wesnoth desktop=entertain
bspc rule -a palapeli desktop=entertain
bspc rule -a FreeTube desktop=entertain

bspc rule -a neochat desktop=entertain
bspc rule -a mirage desktop=entertain

bspc rule -a net-sourceforge-jnlp-runtime-Boot desktop=misc
bspc rule -a sun-awt-X11-XFramePeer desktop=misc
bspc rule -a com-itfinance-core-Starter desktop=misc
bspc rule -a java-lang-Thread desktop=misc


# Tiled {{{2

bspc rule -a Emacs  state=tiled
bspc rule -a Zathura  state=tiled

# Floating {{{2

bspc rule -a XClock                     state=floating rectangle=250x250+1630+50

bspc rule -a URxvt:zshrun               state=floating
bspc rule -a URxvt:zshrunterm           state=floating
bspc rule -a URxvt:fzf-nova             state=floating

bspc rule -a URxvt:calculatrice         state=floating rectangle=964x574+476+50
bspc rule -a URxvt:meteo                state=floating
bspc rule -a URxvt:journal              state=floating rectangle=1200x500+350+50
bspc rule -a URxvt:maintenance          state=floating rectangle=1200x500+350+50
bspc rule -a URxvt:multimedia           state=floating

# bspc rule -a vimiv                      state=floating
# bspc rule -a Sxiv                       state=floating

bspc rule -a Pavucontrol                state=floating
bspc rule -a QjackCtl                   state=floating

bspc rule -a zenity                     state=floating
bspc rule -a Xfce4-appfinder            state=floating
bspc rule -a Pamac-manager              state=floating
bspc rule -a Caja                       state=floating
bspc rule -a "Manjaro Settings Manager" state=floating
bspc rule -a Asunder                    state=floating

bspc rule -a net-sourceforge-jnlp-runtime-Boot state=floating
bspc rule -a sun-awt-X11-XFramePeer            state=floating
bspc rule -a com-itfinance-core-Starter        state=floating
bspc rule -a java-lang-Thread                  state=floating

bspc rule -a neochat state=floating
bspc rule -a quassel state=floating
bspc rule -a Element state=floating

bspc rule -a Wihotspot-gui  state=floating rectangle=964x574+476+50

# Dropdown {{{2

# rectangle=width x height + Xoffset + Yoffset

bspc rule -a kitty:dropdown sticky=on state=floating rectangle=1500x700+200+40
bspc rule -a URxvt:dropdown sticky=on state=floating rectangle=964x574+476+50

bspc rule -a URxvt:calculator sticky=on state=floating rectangle=964x574+476+50
