" vim: set filetype=vim :

" plugins needed before config {{{1

" main {{{1

source ~/racine/config/edit/vim-lite/main.vim

packadd! matchit

" viminfo {{{1

set viminfo=
	\!,
	\f1,
	\h,
	\<12,
	\s12,
	\'120,
	\:10000,
	\/10000,
	\@10000,
	\n~/racine/session/vim-lite/main.viminfo

"set viminfofile=~/racine/session/vim-lite/main.viminfo

" Remplacé par wheel mru
" 	\%30,

" plugins needed before config {{{1

" main {{{1

source ~/racine/config/edit/vim-lite/main.vim

" auto-commands {{{1

source ~/racine/config/edit/vim-lite/autocommand.vim

" python {{{1

if ['arch', 'manjaro', 'artix', 'void', 'ubuntu', 'linux']->index($OPERASYS) >= 0
	let g:python3_host_prog = '/bin/python3'
	let g:python_host_prog = '/bin/python2'
elseif $OPERASYS == 'freebsd'
	let g:python3_host_prog = '/usr/local/bin/python3'
	let g:python_host_prog = '/usr/local/bin/python2'
endif

" all remaining plugins {{{1

source ~/racine/config/edit/vim-lite/paquet/packager.vim
source ~/racine/config/edit/vim-lite/paquet/preload.vim

" load everything to be able to use some conf functions

packloadall

" plugins autoload functions call have to stand after packloadall

source ~/racine/config/edit/vim-lite/paquet/postload.vim

" maps replacing plugins ones {{{1

" plugins auto-commands {{{1

source ~/racine/config/edit/vim-lite/paquet/autocmd-plugin.vim

