" vim: set filetype=vim :

" plugins needed before config {{{1

" main {{{1

source ~/racine/config/edit/vim-lite/main.vim

packadd! matchit

" plugins {{{1

source ~/racine/config/edit/vim-lite/paquet/packager.vim

source ~/racine/config/edit/vim-lite/paquet/preload.vim

" On charge tout, pour pouvoir utiliser certaines fonctions
" de configuration

packloadall

" Les appels aux fonctions autoload des plugins
" doivent se situer après packloadall

source ~/racine/config/edit/vim-lite/paquet/postload.vim

" maps replacing plugins ones {{{1

" plugins auto-commands {{{1

source ~/racine/config/edit/vim-lite/paquet/autocmd-plugin.vim
