# vim: set ft=zsh :

setopt nullglob

# Système d’exploitation {{{1

case $(uname -a) in

	*Linux*ARCH*)
		OPERASYS=archlinux
		;;
	*FreeBSD*)
		OPERASYS=freebsd
		;;
	*Linux*|*linux*)
		OPERASYS=linux
		;;
	?*)
		OPERASYS=inconnu
		;;
esac

if [ -f /etc/arch-release ]
then
	OPERASYS=archlinux
fi

export OPERASYS

# }}}1

#  Type de terminal {{{1

# Nécessaire pour une bonne gestion des couleurs dans tmux, mutt

case "$TERM" in

	linux*) TERM=linux;;

	xterm*) TERM=xterm-256color;;

	tmux*) TERM=tmux-256color;;

	screen*) TERM=screen-256color;;
esac

export TERM

# }}}1

#  Self (zsh configure zsh) {{{1

export RACINE_ZSH=~/racine/config/cmdline/zsh

export SHELL=zsh

export ZDOTDIR=$HOME

export WORDCHARS="*?_-.[]~=&;!#$%^(){}<>"

export PROMPT RPROMPT

#  Historique {{{2

export HISTFILE=~/racine/hist/zsh/$HOST

export SAVEHIST=60000

export HISTSIZE=$SAVEHIST

export HISTFILESIZE=$HISTSIZE

# }}}2

# Piles de répertoires {{{2

export DIRSTACKSIZE=300

export REPERTOIRES_FICHIER="$HOME/racine/hist/zsh/dirs-$HOST"

# }}}2 

#  Chemins {{{2

# Documentation (man) {{{3

typeset -U manpath

manpath=()

manpath+=(/usr/local/share/man)
manpath+=(/usr/share/man)
manpath+=(/usr/local/man)

#export MANPATH=/usr/local/share/man:/usr/share/man

#export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"

# }}}3

#  Documentation (info) {{{3

#export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

#  }}}3

#  Fichiers indexés (locate) {{{3

# Désactivé pour ne pas que la base de donnée soit reprise 2 x
# Voir : 
#   - alias.zsh : alias à locat -
#   - emacs : helm-locate

#export LOCATE_PATH=~/racine/self/locate.db

#  }}}3

# Exécutables {{{3

# Déplacé dans <url:~/racine/config/cmdline/zsh/zprofile>

# Nécessaire car zsh source /etc/profile
# (qui réécrit PATH) après ~/.zshenv

# }}}3

# Fonctions {{{3

typeset -U fpath

# fpath=(~/racine/dotdir/zsh/autoload/*(F) $fpath)
# fpath=(~/racine/dotdir/zsh/completion/*(F) $fpath)

fpath+=(~/racine/dotdir/zsh/autoload/*(F))
fpath+=(~/racine/dotdir/zsh/completion/*(F))

# }}}3

# Répertoires {{{3

typeset -U cdpath

#cdpath=($cdpath ~)
#cdpath=($cdpath ~/art ~/sci)
#cdpath=($cdpath ~/bin ~/install ~/racine/xtens)
#cdpath=($cdpath ~/racine/config ~/retc)
#cdpath=($cdpath ~/src ~/vcs)
#cdpath=($cdpath ~/racine/data ~/racine/var ~/log)

# }}}3

# Personnalisés {{{3

#typeset -TU CHEMINS_PERSONNELS chemins_personnels

# }}}3

# }}}2

#  Tâches {{{2

# Tâches périodiques
#
# Temps en secondes

export PERIOD=300

# Affiche le temps utilisé par
# une commande au-dessus d'un
# certain seuil
#
# Temps en secondes

export REPORTTIME=300

# Temps d'attente avant de considérer
# une combinaison clavier ambiguë comme terminée
#
# Temps en centièmes de secondes

export KEYTIMEOUT=127

# }}}2

#  Courriel {{{2

typeset -U mailpath

repertoires=(\
	~/racine/mail/Systeme/Reception \
	~/racine/mail/Themes/Finance/*(.) \
	/var/spool/mail/$USER \
)

for boite in $repertoires
do
	mailpath[$#mailpath+1]="${boite}?Nouveau courrier dans ${boite:t:r}."
done

export MAIL=/var/spool/mail/$USER

export MAILCHECK=36

# }}}2

# }}}1

#  Nom de l'ordinateur {{{1

export HOST=`hostname -s`
export HOSTNAME=$HOST

# }}}1

# Perso {{{1

source $RACINE_ZSH/perso.zsh

# }}}1

#  Masque {{{1

umask 0022

# }}}1

#  Couleurs & Effets {{{1

source $RACINE_ZSH/couleurs.zsh

# }}}1

#  Compilation {{{1

# C / C++ ... {{{2

#   CC          C compiler command
#   CFLAGS      C compiler flags
#   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
#               nonstandard directory <lib dir>
#   LIBS        libraries to pass to the linker, e.g. -l<library>
#   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
#               you have headers in a nonstandard directory <include dir>
#   CPP         C preprocessor
#   XMKMF       Path to xmkmf, Makefile generator for X Window System

#export CC=gcc

#CFLAGS="-O2 -march=native -mtune=native"
#CFLAGS="$CFLAGS -Wall -Wstrict-prototypes"
#CFLAGS="$CFLAGS -Wno-error=strict-prototypes -Wno-error=deprecated-declarations"
#CFLAGS="$CFLAGS -v"

#CFLAGS="$CFLAGS -pthread -fPIC -fwrapv -fno-strict-aliasing"

#export CFLAGS

# }}}2

# Lisp {{{2

#export LISP=sbcl

# }}}2

# Go {{{2

export GOPATH=~/racine/bin/go

# }}}2

# Linuxbrew {{{2

export HOMEBREW_CC=gcc

# }}}2

# Compilation de vim {{{2

# Pour vim
#
# export CONF_OPT_GUI='--enable-gnome-check'
# export CONF_OPT_LUA='--enable-luainterp'
# export CONF_OPT_PERL='--enable-perlinterp'
# export CONF_OPT_PYTHON='--enable-pythoninterp'
# export CONF_OPT_TCL='--enable-tclinterp'
# export CONF_OPT_RUBY='--enable-rubyinterp'
# export CONF_OPT_MZSCHEME='--disable-mzschemeinterp'
# export CONF_OPT_CSCOPE='--enable-cscope'
# export CONF_OPT_MULTIBYTE='--enable-multibyte'
# export CONF_OPT_FEAT='--with-features=huge'
# export CONF_OPT_COMPBY='"--with-compiledby=antoine.mechelynck@gmail.com"'
# export CONF_ARGS=''

# }}}2

# }}}1

# Réseau {{{1

#export RSH=ssh

# }}}1

# Répertoire temporaire {{{1

export TMPDIR=/tmp
#export TMPDIR=~/tmp

# }}}1

#  Cmdline {{{1

export INPUTRC=~/racine/config/cmdline/inputrc

export RLWRAP_HOME=~/racine/config/cmdline/rlwrap

# Édition de la ligne de commande readline dans un éditeur externe,
# activé par Ctrl-^ par défaut

export RLWRAP_EDITOR='vim -u ~/racine/config/edit/vim/minivim.vim +%L'

# }}}1

#  Utilitaires {{{1

[ $OPERASYS != freebsd ] && {

	eval $(dircolors -b $RACINE_ZSH/../shell/dircolors.conf)
}

export GREP_COLORS='ms=01;31:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'

# }}}1

#  Pageurs {{{1

# Less {{{2

export PAGER=less
export MANPAGER=less

# LESS="--no-init --quit-if-one-screen --raw-control-chars --ignore-case --status-column"
# LESS="$LESS --buffers=360 --tabs=4 --jump-target=.36"
# LESS="$LESS --window=-4 --shift=.36 --max-forw-scroll=36 --max-back-scroll=36"
# LESS="$LESS --LONG-PROMPT --prompt=M?f%f:[Tube]. ?m (%x) No %i/%m:. ?ljLigne %l.?L/%L:. ?djPage %dj:.?D/%D:. ?pPct %pj:."

# export LESS

# Voir ~/racine/config/visu/less/key

# export LESSOPEN="|| ~/bin/shell/visu/lesspipe.sh %s"
# export LESSCLOSE="-"

export LESSHISTFILE=~/racine/hist/less/lesshst
export LESSHISTSIZE=12347

export LESSEDIT='%E ?lm+%lm. %f'

export LESSECHO=lessecho

# Couleurs {{{3

# LESS_TERMCAP_md # begin bold
# LESS_TERMCAP_us # begin underline
# LESS_TERMCAP_mb # begin blinking
# LESS_TERMCAP_so # begin standout-mode - info box

export LESS_TERMCAP_md=$'\E[0;31m'

#export LESS_TERMCAP_us=$'\E[4m'$'\E[1;30m'
export LESS_TERMCAP_us=$'\E[0;33m'

export LESS_TERMCAP_mb=$'\E[5m'

export LESS_TERMCAP_so=$'\E[7m'
#export LESS_TERMCAP_so=$'\E[0;33m'

# LESS_TERMCAP_me # end mode
# LESS_TERMCAP_ue # end underline
# LESS_TERMCAP_se # end standout-mode

export LESS_TERMCAP_me=$'\E[0m'

export LESS_TERMCAP_se=$'\E[0m'

export LESS_TERMCAP_ue=$'\E[0m'

# }}}3

# }}}2

# Most {{{2

export MOST_EDITOR='vim -u ~/racine/config/edit/vim/varia/cf-minivim.vim'
export MOST_SWITCHES='-s'

# }}}2

# }}}1

#  Editeurs {{{1

# un VRAI éditeur de texte ;)

export VISUAL=vim

export EDITOR=vim

export DIFFPROG=vimdiff

export FCEDIT=vim

export SUDO_EDITOR='vim'

# Pour emacs

# Pour helm

export EMACSLOADPATH="~/racine/plugin/manager/el-get/emacs-async:"

# Eshell

export ESHELL=zsh

# Tags

export GTAGSCONF=~/racine/config/edit/labels/gtags.conf

export GTAGSLABEL=native
#export GTAGSLABEL=ctags

# }}}1

#  VCS {{{1

#export RCSINIT=''

export CVSROOT=:local:~/racine/repo/central/cvsroot

#export CVSROOT=:ext:$USER@tixu.local:/home/$USER/racine/repo/cvs

#export CVS_RSH=ssh

#export GIT_DIR=./.git

# }}}1

#  Synchronisation {{{1

export RSYNC_RSH=ssh

export UNISON=~/racine/config/sync/unison/archive/$HOST

#export UNISONLOCALHOSTNAME=$HOST

# }}}1

# Calcul scientifique {{{1

# Octave

export OCTAVE_HISTFILE=~/racine/hist/octave/octave_hist
export OCTAVE_HISTSIZE=34712

# }}}1 

#  Bases de données {{{1

export PGDATA=~/db/postgresql
#export PGUSER=$USER
#export PGHOST=localhost
#export PGPORT=5432

# }}}1

#  Langages de script (perl, python, ruby, ...) {{{1

# Perl

# Python

export PYTHONPATH=~/racine/bin/python:$PYTHONPATH

# Ruby

export RUBYPATH=~/racine/bin/ruby
export RUBYLIB=~/racine/ruby/lib
#export RUBYOPT=

# }}}1

#  Navigateurs {{{1

export BROWSER=qutebrowser

export WWW_HOME="https://start.duckduckgo.com"

# }}}1

#  Java {{{1

# export JAVA_HOME=~/soft/mach/jre1.7.0_21

# export JAVA_ARGS="-Xms256m -Xmx512m"
# export JAVA_OPTS="-Xms256m -Xmx512m"

# export _JAVA_OPTIONS="-Xms256m -Xmx512m"

# }}}1

#  Multimedia {{{1

export MPLAYER_VERBOSE=0

# Voir aussi mpd.conf

export MPD_PORT=6600

# Nécessaire pour dvdauthor
#export VIDEO_FORMAT=PAL

# }}}1

#  Nouvelles {{{1

export NNTPSERVER=news.gmane.org

export SLRN_ROOT=~/nouvelles/spool

# }}}1

#  Alphanumeriques {{{1

# typeset -U chiffres alphabet_minuscule alphabet_majuscule alphanumerique
#
# chiffres=(0 1 2 3 4 5 6 7 8 9)
#
# alphabet_minuscule=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
# alphabet_majuscule=(A B C D E F G H I J K L M N O P Q R S T U V W X Y Z)
#
# alphanumerique=($chiffres $alphabet_majuscule $alphabet_minuscule)

# }}}1

#  Jeux {{{1

#export FREECIV_PATH=${HOME}/data/alter/jeux/freeciv:${HOME}/config/jeux/freeciv:/usr/share/games/freeciv
#export FREECIV_DATA_PATH=${HOME}/data/alter/jeux/freeciv
#export FREECIV_SAVE_PATH=${HOME}/data/alter/jeux/freeciv/saves

# }}}1
