background="#000000"
text="#5b3c11"
subtle="#3b3c11"
warning-text="#88421d"
text-special-one="#88421d"
text-special-two="#872e30"
top-bar-background="#121207"
top-bar-text="#9b5c11"
status-bar-background="#121207"
status-bar-text="#9b5c11"
status-bar-view-background="#121207"
status-bar-view-text="#9b7c11"
command-text="#f8f8f2"
list-selected-background="#070707"
list-selected-text="#9b3c11"
list-selected-inactive-background="#070707"
list-selected-inactive-text="#6b4c11"
controls-text="#5b3c11"
controls-highlight="#9b3c11"
autocomplete-background="#070707"
autocomplete-text="#88421d"
autocomplete-selected-background="#5b3c11"
autocomplete-selected-text="#000000"
button-color-one="#88421d"
button-color-two="#120705"
timeline-name-background="#120705"
timeline-name-text="#875e30"
