
# theme = "adwaita-dark"
# theme = "amberwood"
# theme = "autumn"
# theme = "autumn_night"
# theme = "ayu_dark"
# theme = "dark_high_contrast"
# theme = "dark_plus"
# theme = "everforest_dark"
# theme = "fleet_dark"
# theme = "gruvbox_dark_hard"
theme = "golden-night"
# theme = "heisenberg"
# theme = "hex_lavender"
# theme = "jellybean"
# theme = "kanagawa"
# theme = "mellow"
# theme = "meliora"
# theme = "monokai"
# theme = "monokai_pro_spectrum"
# theme = "noctis_bordo"

[editor]
auto-info = true
bufferline = "multiple"
color-modes = true
line-number = "relative"
text-width = 80
scrolloff = 5
shell = ["zsh", "-c"]
auto-completion = true
idle-timeout = 400
completion-trigger-len = 2
mouse = true
middle-click-paste = true
scroll-lines = 3

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 12

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
#space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
#space = "·"
nbsp = "⍽"
#tab = "→"
#newline = "⏎"
#tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.lsp]
enable = true
auto-signature-help = true
display-inlay-hints = true
snippets = true

[editor.statusline]
left = ["mode", "spinner", "selections", "primary-selection-length"]
center = ["file-name", "file-modification-indicator", "file-encoding", "file-type", "version-control"]
right = ["diagnostics", "position", "position-percentage", "total-line-numbers", "file-line-ending"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
# G = "goto_file_end"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
# V = ["extend_line_below", "select_mode"]
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
"A-$" = "shell_keep_pipe"
"ù" = "file_picker"
C-pagedown = ":buffer-next" # Maps `ga` to show possible code actions
C-pageup = ":buffer-previous" # Maps `ga` to show possible code actions
C-del = ":buffer-close"
"@" = "replay_macro"
"backspace" = "extend_line_below"
"µ" = ["extend_line_below", "select_mode"]
"x" = "delete_selection"
"del" = "delete_selection"

[keys.normal.space]
e = ":reload"
c = ":config-open"
t = ":tutor"
Z = ":write-quit-all"
Q = ":quit-all!"

[keys.normal.Z]
j = "scroll_down"
k = "scroll_up"
u = "half_page_up"
d = "half_page_down"
b = "page_up"
f = "page_down"
Z = ":write-quit-all"
Q = ":quit-all!"

[keys.normal.z]
r = ":config-reload"

[keys.normal.g]
a = "code_action" # Maps `ga` to show possible code actions
t = ":buffer-next" # Maps `ga` to show possible code actions
T = ":buffer-previous" # Maps `ga` to show possible code actions

[keys.select]
# visual mode
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
# k = ["extend_line_up", "extend_to_line_bounds"]
# j = ["extend_line_down", "extend_to_line_bounds"]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
# G = "goto_file_end"
"A-$" = "shell_keep_pipe"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

# [keys.insert.j]
# k = "normal_mode" # Maps `jk` to exit insert mode
# j = { k = "normal_mode" }

# create a new minor mode bound to `+`
# [keys.normal."+"]
# m = ":run-shell-command make"
# c = ":run-shell-command cargo build"
# t = ":run-shell-command cargo test"
